In [62]:
import pandas as pd

In [64]:
df = pd.read_csv('./decks_csv/CLV/clv_artisan.csv')

In [38]:
df.head()

   colorCode        colorName  hexCode
0          1  Hint of Vanilla  #eee8dc
1          2    Elusive White  #e8e3d6
2          3    Nilla Vanilla  #f1ebe0
3          4  Child of Heaven  #f1ebe0
4          5            Kiara  #f5ecdc

In [50]:
df['colorCode'] = df['colorCode'].map(lambda x: str(x))

In [51]:
df.head()

  colorCode        colorName  hexCode
0         1  Hint of Vanilla  #eee8dc
1         2    Elusive White  #e8e3d6
2         3    Nilla Vanilla  #f1ebe0
3         4  Child of Heaven  #f1ebe0
4         5            Kiara  #f5ecdc

In [52]:
type(df['colorCode'][0])

str

In [54]:
def prefixCodeWith0(code):
    if len(code) == 1:
        return '000' + code
    elif len(code) == 2:
        return '00' + code
    elif len(code) == 3:
        return '0' + code
    return code

df['colorCode'] = df['colorCode'].map(prefixCodeWith0)

In [56]:
df.sample()

    colorCode      colorName  hexCode
258      0259  Persian Fable  #d2bb9c

In [59]:
csv = df.to_csv('decks/CLV/clv_artisan1.csv', index=False)

In [73]:

df = pd.read_csv('decks_csv/SW/emerald_designer.csv')
json = df.to_json('decks_json/SW/emerald_designer.json', orient='records')